services:
  # PostgreSQL database
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 8273
      POSTGRES_DB: financial
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - C:\Users\Vanessa Castanho\Documents\Programming\Shiny_Dashboard_ITUB4\data\sql_files\:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Client 1 app
  client1:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CLIENT_ID=1
    volumes:
      - ./app_client_1.R:/srv/shiny-server/app.R
      - ./global.R:/srv/shiny-server/global.R
    ports:
      - "3838:3838"

  # Client 2 app
  client2:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CLIENT_ID=2
    volumes:
      - ./app_client_2.R:/srv/shiny-server/app.R
      - ./global.R:/srv/shiny-server/global.R
    ports:
      - "3839:3838"

volumes:
  postgres_data: